/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput/index.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage/index.vue')['default']
    ChatMessageList: typeof import('./src/components/ChatMessageList/index.vue')['default']
    EmotionReport: typeof import('./src/components/EmotionReport/index.vue')['default']
    LayoutCenterPanel: typeof import('./src/components/Layout/CenterPanel.vue')['default']
    LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
    LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
    LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
    NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    NavigationNavFooter: typeof import('./src/components/Navigation/NavFooter.vue')['default']
    NavigationNavOctocat: typeof import('./src/components/Navigation/NavOctocat.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionHeader: typeof import('./src/components/SessionHeader/index.vue')['default']
    SessionList: typeof import('./src/components/SessionList/index.vue')['default']
    SideBarItem: typeof import('./src/components/SideBar/Item.vue')['default']
  }
}

// For TSX support
declare global {
  const 404: typeof import('./src/components/404.vue')['default']
  const ChatInput: typeof import('./src/components/ChatInput/index.vue')['default']
  const ChatMessage: typeof import('./src/components/ChatMessage/index.vue')['default']
  const ChatMessageList: typeof import('./src/components/ChatMessageList/index.vue')['default']
  const EmotionReport: typeof import('./src/components/EmotionReport/index.vue')['default']
  const LayoutCenterPanel: typeof import('./src/components/Layout/CenterPanel.vue')['default']
  const LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
  const LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
  const LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
  const NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
  const NavigationNavFooter: typeof import('./src/components/Navigation/NavFooter.vue')['default']
  const NavigationNavOctocat: typeof import('./src/components/Navigation/NavOctocat.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NEllipsis: typeof import('naive-ui')['NEllipsis']
  const NFloatButton: typeof import('naive-ui')['NFloatButton']
  const NInput: typeof import('naive-ui')['NInput']
  const NList: typeof import('naive-ui')['NList']
  const NListItem: typeof import('naive-ui')['NListItem']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NPopconfirm: typeof import('naive-ui')['NPopconfirm']
  const NProgress: typeof import('naive-ui')['NProgress']
  const NResult: typeof import('naive-ui')['NResult']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NTag: typeof import('naive-ui')['NTag']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SessionHeader: typeof import('./src/components/SessionHeader/index.vue')['default']
  const SessionList: typeof import('./src/components/SessionList/index.vue')['default']
  const SideBarItem: typeof import('./src/components/SideBar/Item.vue')['default']
}